### ISSUE TITLE
Is it OK to refer to `UIImageNibPlaceholder`?

### ISSUE THREAD

**Issue by zubko** [accidbright/ABImageLoader#1]
`UIImageNibPlaceholder` is a private API. Although a harmless one. 
But anyways, did you submit successfully an app with `ABImageLoader` to the App Store?

**Comment by accidbright** [comment]
No. I haven't submit the app yet. But this piece of code was found somewhere in other sources (from where I got the idea of swizzling implementation). Those sources were successfully submitted to the App Store by my collegue. So I think, there shouldn't be any problem.
In any case, there is possible to delete this piece of code (if you are afraid of rejecting) and don't use loading from storyboard/XIB (only will work with `imageNamed:` method).

**Comment by accidbright** [comment]
The app with these soursees approved by Apple.
